line-length = 79
target-version = "py310"

fix = true
unsafe-fixes = false

exclude = [
  ".git",
  ".venv",
  "__pycache__",
  "staticfiles",
  "migrations",
  "db.sqlite3",
]

[lint]
select = ["E", "F", "I"]
ignore = []

[lint.isort]
known-first-party = [
  "task_manager",
  "users",
  "statuses",
  "tasks",
  "labels",
]
